#!/bin/sh
OS=`uname -s`
HOST=`uname -n`

cd /pub/sfc/ipl/typing

if [ $OS = 'Darwin' ]
then
    if [ $# -eq 1 ]
    then
	LOCALE=$1
    else
	L=`defaults read -g AppleLocale`
	if [ $L = 'ja_JP' ]
	then
	    if [ $DISPLAY ]
	    then
		LOCALE='ja_JP.eucJP'
	    else
		LOCALE='ja_JP.UTF-8'
	    fi
	else
	    LOCALE='en'
	fi
    fi
    if [ ${DISPLAY} ]
    then
	kterm -xrm '*.vt100.translations: #override <Btn2Up>:bell(100)\n <KeyPress>BackSpace:string(0x7f)\n' \
	    -km euc -fn \*-fixed-medium-r-normal--24-\*-iso8859-1 \
	    -fr \*-fixed-medium-r-normal--24-\*-jisx0201\* \
	    -fk -jis-fixed-medium-r-normal--24-\*-jisx0208\* \
	    -fkb -jis-fixed-medium-r-normal--24-\*-jisx0208\* \
	    -fb \*-fixed-medium-r-normal--24-\*-iso8859-1 \
	    -frb \*-fixed-medium-r-normal--24-\*-jisx0201\* \
	    -title 'TYPING TEST' \
	    -e ./typing-mac --hide-type-pra $LOCALE
    else
	./typing-mac --hide-type-pra $LOCALE
    fi
elif [ $OS = 'SunOS' ]
then
    ./typing-solaris --hide-type-pra $LANG
elif [ $OS = 'Linux' ]
then
    ./typing-linux --hide-type-pra $LANG
else
    echo 'Not supported currently on this machine.'
fi
